name: Tests

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install frontend dependencies
        run: npm ci

      - name: Create Firebase secrete json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "firebase-key.json"
          json: ${{ secrets.FIREBASE_KEY }}
          dir: ""

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set Firebase environment variables
        run: echo "FIRESTORE_EMULATOR_HOST=localhost:8080" >> $GITHUB_ENV

      - name: Start Firebase Emulator
        run: |
          firebase emulators:start --only firestore --project algo-graveyard &
          echo $! > emulator_pid.txt
        env:
          CI: true

      - name: Run tests
        run: |
          pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=app tests/ \
            > pytest-coverage.txt
          echo $(cat pytest-coverage.txt)
          EXIT_CODE=$?
          echo $EXIT_CODE
        continue-on-error: true

      - name: Stop Firebase Emulator
        run: |
          pid=$(cat emulator_pid.txt)
          kill $pid

      - name: Post coverage comment
        if: always()
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml

      - name: Exit the program
        run: |
          echo $EXIT_CODE
          exit $EXIT_CODE
