name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]  # save time, personal project so doesn't matter

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create Firebase secrete json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "firebase-key.json"
          json: ${{ secrets.FIREBASE_KEY }}
          dir: ""
      - name: Run tests
        run:  pytest --cov=app --cov-report=xml --cov-report=term
      - name: Post coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
